language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-24
    - extra

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build assembleAndroidTest

after_success:
  - ./gradlew createRegularMinSdkDebugCoverageReport
  - pip install --user codecov
  - codecov
