language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-23
    - sys-img-x86-android-15
    - add-on
    - extra

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
