language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - sys-img-x86-android-tv-l
    - add-on
    - extra

before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS='-XX:MaxPermSize=1024m -Xmx=1024m'"
